# ~/.config/starship.toml


format = """\
[ mnesbitt ](bg:#c4a7e7 fg:#2a273f)\
[](fg:#c4a7e7 bg:#2a273f)\
$git_branch\
[](fg:#2a273f bg:#e0def4)\
$directory\
[ ](fg:#e0def4 bg:#1E1E2E)\
$character
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#2a273f bg:#e0def4"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style) [$fallback]($style)'
symbol = "  "
style = "fg:#c4a7e7 bg:#2a273f"
fallback = "zsh"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[\$](#A5ADCB)'
#success_symbol = '[](#A5ADCB)'
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2a273f"
format = '[[ zsh ](bg:#2a273f fg:#A5ADCB)]($style)'
